version: "2"

services:
  app:
    image: simplycodedsoftware/ci:7.1
    volumes:
      - "$PWD:/data/app"
      - "$HOME/.ssh:/home/deploy/.ssh"
    user: 1000:1000
    working_dir: "/data/app"
    command: sleep 99999
    networks:
      - default
  postgres:
    image: postgres:10.2
    environment:
      POSTGRES_USER: "admin"
      POSTGRES_PASSWORD: "secret"
      POSTGRES_DB: "cqrs"
    networks:
      - default

networks:
  default:
    driver: bridge